allowBuilds:
  electron-winstaller: set this to true or false
  koffi: set this to true or false
  uiohook-napi: set this to true or false
onlyBuiltDependencies:
  - electron
  - koffi
  - uiohook-napi
